/* eslint-disable */
/* @ts-nocheck */
/* prettier-ignore */
/* This file is automatically generated using `npm run graphql:types` */
import type * as Types from '../../../../generated/types';

import type { JsonObject } from "type-fest";
import gql from 'graphql-tag';
export type TransferMyTicketToUserMutationVariables = Types.Exact<{
  ticketId: Types.Scalars['String']['input'];
  input: Types.UserTicketTransferInfoInput;
}>;


export type TransferMyTicketToUserMutation = { __typename?: 'Mutation', transferMyTicketToUser: { __typename?: 'UserTicketTransfer', id: string, status: Types.TicketTransferAttemptStatus, expirationDate: string, transferMessage: string | null, sender: { __typename?: 'TicketTransferUserInfo', email: string, name: string | null }, recipient: { __typename?: 'TicketTransferUserInfo', email: string, name: string | null }, userTicket: { __typename?: 'UserTicket', id: string, approvalStatus: Types.TicketApprovalStatus } } };


export const TransferMyTicketToUser = gql`
    mutation TransferMyTicketToUser($ticketId: String!, $input: UserTicketTransferInfoInput!) {
  transferMyTicketToUser(ticketId: $ticketId, input: $input) {
    id
    status
    expirationDate
    transferMessage
    sender {
      email
      name
    }
    recipient {
      email
      name
    }
    userTicket {
      id
      approvalStatus
    }
  }
}
    `;