// Generated by Wrangler on Fri Jul 07 2023 08:10:34 GMT-0700 (Pacific Daylight Time)
interface Env {
  ENVIRONMENT: "dev";
  GRAPHQL_BASE_ENDPOINT: "/";
  GRAPHQL_KV_CACHE: "";
}

declare global {
  // Declare types for replace variables
  const _APP_ENV: "development" | "production" | "staging";
  const _AUTH_COOKIE_NAME: string;
}

export {};
