name = "graphql-api-local"
main = "build/index.js"
workers_dev = true
compatibility_date = "2022-09-29"

[build]
command = "npm run generate && npm run build"

[vars]
GRAPHQL_BASE_ENDPOINT = "/"
GRAPHQL_KV_CACHE = ""

[env.production]
name = "graphql-api"
[[env.production.kv_namespaces]]
binding = "GRAPHQL_CACHE"
id = "ba46c41d96544abba4aae3600c4955eb"
[env.production.vars]
GRAPHQL_BASE_ENDPOINT = "/"
GRAPHQL_KV_CACHE = "true"

[env.staging]
name = "graphql-api"
[[env.staging.kv_namespaces]]
binding = "GRAPHQL_CACHE"
id = "ba46c41d96544abba4aae3600c4955eb"
[env.staging.vars]
GRAPHQL_BASE_ENDPOINT = "/"
GRAPHQL_KV_CACHE = "true"
