# 🚨 DEFAULT CONFIG 🚨
name = "graphql-api-dev"
compatibility_date = "2022-09-29"
main = "src/index.ts"

[vars]
GRAPHQL_BASE_ENDPOINT = "/"
GRAPHQL_KV_CACHE = ""

[define]
_APP_ENV = "'development'"
_AUTH_COOKIE_NAME = "'JSCHILE_ORG_AUTH_COOKIE'"



# 🚨 PRODUCTION CONFIG 🚨
[env.production]
name = "graphql-api-prod"
route = "api.jschile.org/*"

[env.production.vars]
GRAPHQL_BASE_ENDPOINT = "/"
GRAPHQL_KV_CACHE = ""

[env.production.define]
_APP_ENV = "'production'"
_AUTH_COOKIE_NAME = "'JSCHILE_ORG_AUTH_COOKIE'"



# 🚨 STAGING CONFIG 🚨
[env.staging]
name = "graphql-api-staging"
route = "api.jsconf.dev/*"

[env.staging.vars]
GRAPHQL_BASE_ENDPOINT = "/"
GRAPHQL_KV_CACHE = ""

[env.staging.define]
_APP_ENV = "'staging'"
_AUTH_COOKIE_NAME = "'JSCHILE_ORG_AUTH_COOKIE'"
