# 🚨 DEFAULT CONFIG 🚨
name = "graphql-api"
compatibility_date = "2024-06-03"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]
observability = { enabled = true }

[dev]
port = 50123

[[services]]
binding = "RPC_SERVICE_EMAIL"
service = "transactional-email-service"

[vars]
GRAPHQL_BASE_ENDPOINT = "/"

[define]
_APP_ENV = "'development'"

# [placement]
# mode = "smart"

[[queues.producers]]
queue = "mail-queue-dev"
binding = "MAIL_QUEUE"

[[queues.producers]]
queue = "google-photos-import-queue-dev"
binding = "GOOGLE_PHOTOS_IMPORT_QUEUE"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "f0bc5f4533eb4557976b7d0b59d880ad"
localConnectionString = "postgresql://fake-user:fake-pasword@fake:5432/fake-db"

# =====================================
# =====================================
# 🚨 PRODUCTION CONFIG 🚨
# =====================================
# =====================================
[env.production]
route = "api.jschile.org/*"
logpush = true
observability = { enabled = true }


[[env.production.services]]
binding = "RPC_SERVICE_EMAIL"
service = "transactional-email-service-production"

[env.production.vars]
GRAPHQL_BASE_ENDPOINT = "/"

[env.production.define]
_APP_ENV = "'production'"

# [env.production.placement]
# mode = "smart"

[[env.production.queues.producers]]
queue = "mail-queue-production"
binding = "MAIL_QUEUE"

[[env.production.queues.producers]]
queue = "google-photos-import-queue-production"
binding = "GOOGLE_PHOTOS_IMPORT_QUEUE"

[[env.production.hyperdrive]]
binding = "HYPERDRIVE"
id = "faa163999e9f40c6a26b3612940bc5ba"


# =====================================
# =====================================
# 🚨 STAGING CONFIG 🚨
# =====================================
# =====================================
[env.staging]
route = "api.jsconf.dev/*"
logpush = true
observability = { enabled = true }

[[env.staging.services]]
binding = "RPC_SERVICE_EMAIL"
service = "transactional-email-service-staging"

[env.staging.vars]
GRAPHQL_BASE_ENDPOINT = "/"

[env.staging.define]
_APP_ENV = "'staging'"

# [env.staging.placement]
# mode = "smart"

[[env.staging.queues.producers]]
queue = "mail-queue-staging"
binding = "MAIL_QUEUE"

[[env.staging.queues.producers]]
queue = "google-photos-import-queue-staging"
binding = "GOOGLE_PHOTOS_IMPORT_QUEUE"

[[env.staging.hyperdrive]]
binding = "HYPERDRIVE"
id = "c693e76575c64a8eab15032d97ab938f"
