# 🚨 DEFAULT CONFIG 🚨
name = "graphql-api-dev"
compatibility_date = "2022-09-29"
main = "src/index.ts"

[vars]
GRAPHQL_BASE_ENDPOINT = "/"
GRAPHQL_KV_CACHE = ""
DATABASE_URL="libsql://6e82d2eeb39748-tickets-staging-fforres.turso.io"

[define]
_APP_ENV = "'development'"
_AUTH_COOKIE_NAME = "'JSCHILE_ORG_AUTH_COOKIE'"

[placement]
mode = "smart"


# 🚨 PRODUCTION CONFIG 🚨
[env.production]
name = "graphql-api-prod"
route = "api.jschile.org/*"

[env.production.vars]
GRAPHQL_BASE_ENDPOINT = "/"
GRAPHQL_KV_CACHE = ""

[env.production.define]
_APP_ENV = "'production'"
_AUTH_COOKIE_NAME = "'JSCHILE_ORG_AUTH_COOKIE'"
# DATABASE_URL="" # SET ON THE DASHBOARD
# DATABASE_URL="" # SET ON THE DASHBOARD

[env.production.placement]
mode = "smart"



# 🚨 STAGING CONFIG 🚨
[env.staging]
name = "graphql-api-staging"
route = "api.jsconf.dev/*"

[env.staging.vars]
GRAPHQL_BASE_ENDPOINT = "/"
GRAPHQL_KV_CACHE = ""

[env.staging.define]
_APP_ENV = "'staging'"
_AUTH_COOKIE_NAME = "'JSCHILE_ORG_AUTH_COOKIE'"
DATABASE_URL="libsql://6e82d2eeb39748-tickets-staging-fforres.turso.io"

[env.staging.placement]
mode = "smart"
