# 🚨 DEFAULT CONFIG 🚨
name = "graphql-api"
compatibility_date = "2023-06-06"
main = "src/index.ts"

[vars]
GRAPHQL_BASE_ENDPOINT = "/"
OTEL_SERVICE_NAME="graphql-api"

[define]
_APP_ENV = "'development'"

[placement]
mode = "smart"

[[queues.producers]]
queue = "mail-queue-dev"
binding = "MAIL_QUEUE"

[[queues.producers]]
queue = "google-photos-import-queue-dev"
binding = "GOOGLE_PHOTOS_IMPORT_QUEUE"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "c485ebbbe7984315b1c7c53f3c579c54"

# =====================================
# =====================================
# 🚨 PRODUCTION CONFIG 🚨
# =====================================
# =====================================
[env.production]
route = "api.jschile.org/*"
logpush = true

[env.production.vars]
GRAPHQL_BASE_ENDPOINT = "/"
OTEL_SERVICE_NAME="graphql-api"

[env.production.define]
_APP_ENV = "'production'"

[env.production.placement]
mode = "smart"

[[env.production.queues.producers]]
queue = "mail-queue-production"
binding = "MAIL_QUEUE"

[[env.production.queues.producers]]
queue = "google-photos-import-queue-production"
binding = "GOOGLE_PHOTOS_IMPORT_QUEUE"

[[env.production.hyperdrive]]
binding = "HYPERDRIVE"
id = "2d834d5b48a34aa998a8c07e571c8cbd"


# =====================================
# =====================================
# 🚨 STAGING CONFIG 🚨
# =====================================
# =====================================
[env.staging]
route = "api.jsconf.dev/*"
logpush = true

[env.staging.vars]
GRAPHQL_BASE_ENDPOINT = "/"
OTEL_SERVICE_NAME="graphql-api"

[env.staging.define]
_APP_ENV = "'staging'"

[env.staging.placement]
mode = "smart"

[[env.staging.queues.producers]]
queue = "mail-queue-staging"
binding = "MAIL_QUEUE"

[[env.staging.queues.producers]]
queue = "google-photos-import-queue-staging"
binding = "GOOGLE_PHOTOS_IMPORT_QUEUE"

[[env.staging.hyperdrive]]
binding = "HYPERDRIVE"
id = "7cbe793201644c8da2d333afc982c114"
