# 🚨 DEFAULT CONFIG 🚨
name = "graphql-api-dev"
compatibility_date = "2023-06-06"
main = "src/index.ts"

[vars]
GRAPHQL_BASE_ENDPOINT = "/"
OTEL_SERVICE_NAME="graphql-api"

[define]
_APP_ENV = "'development'"

[placement]
mode = "smart"


# 🚨 PRODUCTION CONFIG 🚨
[env.production]
name = "graphql-api-prod"
route = "api.jschile.org/*"

[env.production.vars]
GRAPHQL_BASE_ENDPOINT = "/"
OTEL_SERVICE_NAME="graphql-api"

[env.production.define]
_APP_ENV = "'production'"

[env.production.placement]
mode = "smart"

# 🚨 STAGING CONFIG 🚨
[env.staging]
name = "graphql-api-staging"
route = "api.jsconf.dev/*"

[env.staging.vars]
GRAPHQL_BASE_ENDPOINT = "/"
OTEL_SERVICE_NAME="graphql-api"

[env.staging.define]
_APP_ENV = "'staging'"

[env.staging.placement]
mode = "smart"
