# 🚨 DEFAULT CONFIG 🚨
name = "graphql-api"
compatibility_date = "2023-06-06"
main = "src/index.ts"

[vars]
GRAPHQL_BASE_ENDPOINT = "/"
OTEL_SERVICE_NAME="graphql-api"

[define]
_APP_ENV = "'development'"

[placement]
mode = "smart"

[[queues.producers]]
queue = "mail-queue-dev"
binding = "MAIL_QUEUE"

[[queues.consumers]]
queue = "mail-queue-dev"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 10
dead_letter_queue = "deadletter-mail-queue-dev"





# =====================================
# =====================================
# 🚨 PRODUCTION CONFIG 🚨
# =====================================
# =====================================
[env.production]
route = "api.jschile.org/*"

[env.production.vars]
GRAPHQL_BASE_ENDPOINT = "/"
OTEL_SERVICE_NAME="graphql-api"

[env.production.define]
_APP_ENV = "'production'"

[env.production.placement]
mode = "smart"

[[env.production.queues.producers]]
queue = "mail-queue-production"
binding = "MAIL_QUEUE"

[[env.production.queues.consumers]]
queue = "mail-queue-production"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 10
dead_letter_queue = "deadletter-mail-queue-production"





# =====================================
# =====================================
# 🚨 STAGING CONFIG 🚨
# =====================================
# =====================================
[env.staging]
route = "api.jsconf.dev/*"

[env.staging.vars]
GRAPHQL_BASE_ENDPOINT = "/"
OTEL_SERVICE_NAME="graphql-api"

[env.staging.define]
_APP_ENV = "'staging'"

[env.staging.placement]
mode = "smart"

[[env.staging.queues.producers]]
queue = "mail-queue-staging"
binding = "MAIL_QUEUE"

[[env.staging.queues.consumers]]
queue = "mail-queue-staging"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 10
dead_letter_queue = "deadletter-mail-queue-staging"

