# 🚨 DEFAULT CONFIG 🚨
name = "graphql-api"
compatibility_date = "2024-06-03"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 50123

[[services]]
binding = "RPC_SERVICE_EMAIL"
service = "transactional-email-service"

[[services]]
binding = "RPC_SERVICE_DB"
service = "db-service"


[vars]
GRAPHQL_BASE_ENDPOINT = "/"

[define]
_APP_ENV = "'development'"

# [placement]
# mode = "smart"

[[queues.producers]]
queue = "mail-queue-dev"
binding = "MAIL_QUEUE"

[[queues.producers]]
queue = "google-photos-import-queue-dev"
binding = "GOOGLE_PHOTOS_IMPORT_QUEUE"

# =====================================
# =====================================
# 🚨 PRODUCTION CONFIG 🚨
# =====================================
# =====================================
[env.production]
route = "api.jschile.org/*"
logpush = true

[[env.production.services]]
binding = "RPC_SERVICE_EMAIL"
service = "transactional-email-service"

[[env.production.services]]
binding = "RPC_SERVICE_DB"
service = "db-service-prod"


[env.production.vars]
GRAPHQL_BASE_ENDPOINT = "/"

[env.production.define]
_APP_ENV = "'production'"

# [env.production.placement]
# mode = "smart"

[[env.production.queues.producers]]
queue = "mail-queue-production"
binding = "MAIL_QUEUE"

[[env.production.queues.producers]]
queue = "google-photos-import-queue-production"
binding = "GOOGLE_PHOTOS_IMPORT_QUEUE"




# =====================================
# =====================================
# 🚨 STAGING CONFIG 🚨
# =====================================
# =====================================
[env.staging]
route = "api.jsconf.dev/*"
logpush = true

[[env.staging.services]]
binding = "RPC_SERVICE_EMAIL"
service = "transactional-email-service"

[[env.staging.services]]
binding = "RPC_SERVICE_DB"
service = "db-service-prod-staging"

[env.staging.vars]
GRAPHQL_BASE_ENDPOINT = "/"

[env.staging.define]
_APP_ENV = "'staging'"

# [env.staging.placement]
# mode = "smart"

[[env.staging.queues.producers]]
queue = "mail-queue-staging"
binding = "MAIL_QUEUE"

[[env.staging.queues.producers]]
queue = "google-photos-import-queue-staging"
binding = "GOOGLE_PHOTOS_IMPORT_QUEUE"
