name = "graphql-api-dev"
compatibility_date = "2022-09-29"
main = "src/index.ts"

[build]
command = "npm run generate && npm run build"

[vars]
ENVIRONMENT = "dev"
GRAPHQL_BASE_ENDPOINT = "/"
GRAPHQL_KV_CACHE = ""

[env.production]
name = "graphql-api-prod"
route = "api.jschile.org/*"

[env.production.vars]
ENVIRONMENT = "production"
GRAPHQL_BASE_ENDPOINT = "/"
GRAPHQL_KV_CACHE = ""

[env.staging]
name = "graphql-api-staging"
route = "api.jsconf.dev/*"

[env.staging.vars]
ENVIRONMENT = "staging"
GRAPHQL_BASE_ENDPOINT = "/"
GRAPHQL_KV_CACHE = ""
