name = "graphql-api-local"
main = "build/index.js"
workers_dev = true
compatibility_date = "2022-09-29"

[build]
command = "npm run generate && npm run build"

[vars]
GRAPHQL_BASE_ENDPOINT = "/"
GRAPHQL_KV_CACHE = ""

[env.production]
name = "graphql-api"

[env.production.vars]
GRAPHQL_BASE_ENDPOINT = "/"
GRAPHQL_KV_CACHE = ""

[env.staging]
name = "graphql-api"

[env.staging.vars]
GRAPHQL_BASE_ENDPOINT = "/"
GRAPHQL_KV_CACHE = ""
