table allowed_currencies {
  id text [pk, not null]
  currency text(3) [not null, unique]
  payment_methods text
  created_at integer [not null, default: `current_timestamp`]
  updated_at integer
  deleted_at integer
}

table communities {
  id text [pk, not null]
  name text [not null]
  slug text(64) [unique]
  description text(1024)
  status text [not null, default: 'inactive']
  created_at integer [not null, default: `current_timestamp`]
  updated_at integer
  deleted_at integer
}

table companies {
  company_id text [pk, not null, unique]
  name text
  description text
  domain text [not null]
  logo text
  website text
  created_at integer [not null, default: `current_timestamp`]
  updated_at integer
  deleted_at integer
}

table events {
  id text [pk, not null]
  name text(1024) [not null, unique]
  description text(4096)
  status text [not null, default: 'inactive']
  visibility text [not null, default: 'unlisted']
  start_date_time integer [not null]
  end_date_time integer
  timezone text(64)
  geo_latitude text
  geo_longitude text
  geo_address_json text
  meeting_url text
  max_attendees integer
  created_at integer [not null, default: `current_timestamp`]
  updated_at integer
  deleted_at integer
}

table events_communities {
  event_id text [not null]
  community_id text [not null]
  created_at integer [not null, default: `current_timestamp`]
  updated_at integer
  deleted_at integer

  indexes {
    (event_id, community_id) [pk]
  }
}

table events_tags {
  event_id text
  tag_id text
  created_at integer [not null, default: `current_timestamp`]
  updated_at integer
  deleted_at integer

  indexes {
    (event_id, tag_id) [pk]
  }
}

table events_users {
  event_id text
  user_id text
  role text [default: 'member']
  created_at integer [not null, default: `current_timestamp`]
  updated_at integer
  deleted_at integer
}

table salaries {
  company_id text [pk, not null, unique]
  user_id text [not null]
  amount integer [not null]
  currency text
  work_role_id text
  years_of_experience integer [not null]
  country_code text [not null]
  type_of_employment text [not null]
  work_metodology text [not null]
  created_at integer [not null, default: `current_timestamp`]
  updated_at integer
  deleted_at integer
}

table tags {
  id text [pk, not null]
  name text [not null, unique]
  description text(1024)
  created_at integer [not null, default: `current_timestamp`]
  updated_at integer
  deleted_at integer
}

table tags_communities {
  tag_id text
  community_id text
  created_at integer [not null, default: `current_timestamp`]
  updated_at integer
  deleted_at integer

  indexes {
    (tag_id, community_id) [pk]
  }
}

table tickets {
  id text [pk, not null]
  name text(1024) [not null, unique]
  description text(4096)
  status text [not null, default: 'inactive']
  visibility text [not null, default: 'unlisted']
  start_date_time integer [not null]
  end_date_time integer
  requires_approval integer [default: false]
  price integer
  quantity integer
  event_id text [not null]
  currency text
  created_at integer [not null, default: `current_timestamp`]
  updated_at integer
  deleted_at integer
}

table users {
  id text [pk, not null]
  name text
  lastName text
  bio text(1024) [default: '']
  email text
  gender text
  gender_other_text text
  isSuperAdmin integer [default: false]
  emailVerified integer
  imageUrl text
  username text(64) [not null, unique]
  twoFactorEnabled integer
  unsafeMetadata blob
  publicMetadata blob
  created_at integer [not null, default: `current_timestamp`]
  updated_at integer
  deleted_at integer
}

table users_communities {
  user_id text
  community_id text
  role text [default: 'member']
  created_at integer [not null, default: `current_timestamp`]
  updated_at integer
  deleted_at integer
}

table user_tickets {
  id text [pk, not null]
  user_id text
  ticket_template_id text [not null]
  status text [not null, default: 'cancelled']
  payment_status text [not null, default: 'unpaid']
  approval_status text [not null, default: 'pending']
  redemption_status text [not null, default: 'pending']
  created_at integer [not null, default: `current_timestamp`]
  updated_at integer
  deleted_at integer
}

table work_email {
  id text [pk, not null, unique]
  user_id text [not null]
  work_email text [not null]
  confirmation_token text
  is_confirmed integer [default: false]
  confirmation_date integer
  company_id text
  created_at integer [not null, default: `current_timestamp`]
  updated_at integer
  deleted_at integer
}

table work_role {
  company_id text [pk, not null, unique]
  name text [not null]
  description text [not null]
  created_at integer [not null, default: `current_timestamp`]
  updated_at integer
  deleted_at integer
}

ref: events_communities.community_id > communities.id

ref: events_communities.event_id > events.id

ref: events_tags.event_id > events.id

ref: events_tags.tag_id > tags.id

ref: events_users.event_id - events.id

ref: events_users.user_id - users.id

ref: salaries.currency - allowed_currencies.id

ref: salaries.work_role_id - work_role.company_id

ref: salaries.user_id - users.id

ref: tags_communities.community_id > communities.id

ref: tags_communities.tag_id > tags.id

ref: tickets.event_id > events.id

ref: tickets.currency - allowed_currencies.id

ref: users_communities.community_id > communities.id

ref: users_communities.user_id > users.id

ref: user_tickets.ticket_template_id > tickets.id

ref: user_tickets.user_id > users.id

ref: work_email.company_id - companies.company_id

ref: work_email.user_id - users.id