mutation CancelUserTicketAddons($userTicketAddonIds: [String!]!) {
  cancelUserTicketAddons(userTicketAddonIds: $userTicketAddonIds) {
    id
    approvalStatus
    quantity
    addonId
    userTicketId
  }
}
