/* eslint-disable */
/* @ts-nocheck */
/* prettier-ignore */
/* This file is automatically generated using `npm run graphql:types` */
import type * as Types from '../../../../generated/types';

import type { JsonObject } from "type-fest";
import gql from 'graphql-tag';
export type AcceptGiftedTicketMutationVariables = Types.Exact<{
  giftId: Types.Scalars['String']['input'];
}>;


export type AcceptGiftedTicketMutation = { __typename?: 'Mutation', acceptGiftedTicket: { __typename?: 'UserTicket', id: string, paymentStatus: Types.PurchaseOrderPaymentStatusEnum | null, approvalStatus: Types.TicketApprovalStatus, redemptionStatus: Types.TicketRedemptionStatus } };


export const AcceptGiftedTicket = gql`
    mutation AcceptGiftedTicket($giftId: String!) {
  acceptGiftedTicket(giftId: $giftId) {
    id
    paymentStatus
    approvalStatus
    redemptionStatus
  }
}
    `;