# 🚨 DEFAULT CONFIG 🚨
name = "purchase-order-payment-sync-cron"
compatibility_date = "2024-06-03"
main = "./index.ts"
node_compat = true
upload_source_maps = true

[vars]
# Variables should go here

[triggers]
# Schedule cron triggers:
# - Every day
crons = ["* */1 * * *"]

[define]
_APP_ENV = "'development'"

[[services]]
binding = "RPC_SERVICE_EMAIL"
service = "transactional-email-service"

# =====================================
# =====================================
# 🚨 PRODUCTION CONFIG 🚨
# =====================================
# =====================================
[env.production]
logpush = true

[env.production.vars]
# Variables should go here

[[env.production.services]]
binding = "RPC_SERVICE_EMAIL"
service = "transactional-email-service-production"

[env.production.triggers]
# Schedule cron triggers:
# - Every 1 minute
crons = ["*/1 * * * *"]

[env.production.define]
_APP_ENV = "'production'"


# =====================================
# =====================================
# 🚨 STAGING CONFIG 🚨
# =====================================
# =====================================
[env.staging]
logpush = true

[env.staging.vars]
# Variables should go here

[env.staging.triggers]
# Schedule cron triggers:
# - Every day
crons = ["* */1 * * *"]

[env.staging.define]
_APP_ENV = "'staging'"

[[env.staging.services]]
binding = "RPC_SERVICE_EMAIL"
service = "transactional-email-service-staging"
