/* eslint-disable */
/* @ts-nocheck */
/* prettier-ignore */
/* This file is automatically generated using `npm run graphql:types` */
import type * as Types from '../../generated/types';

import type { JsonObject } from "type-fest";
import gql from 'graphql-tag';
export type UpdateUserRoleInCommunityMutationVariables = Types.Exact<{
  input: Types.UpdateUserRoleInCommunityInput;
}>;


export type UpdateUserRoleInCommunityMutation = { __typename?: 'Mutation', updateUserRoleInCommunity: { __typename?: 'User', id: string, name: string | null, bio: string | null, lastName: string | null, username: string } };


export const UpdateUserRoleInCommunity = gql`
    mutation UpdateUserRoleInCommunity($input: updateUserRoleInCommunityInput!) {
  updateUserRoleInCommunity(input: $input) {
    id
    name
    bio
    lastName
    username
  }
}
    `;