mutation CreateEvent($input: EventCreateInput!) {
  createEvent(input: $input) {
    id
    name
    description
    visibility
    status
    startDateTime
    endDateTime
  }
}

query CommunityEvents($communityId: String!) {
  community(id: $communityId) {
    id
    events {
      id
      name
      visibility
      status
    }
  }
}
