query Events($input: PaginatedInputEventsSearchInput!) {
  searchEvents(input: $input) {
    data {
      id
      name
      description
      visibility
      status
      startDateTime
      endDateTime
    }
    pagination {
      currentPage
      pageSize
      totalPages
      totalRecords
    }
  }
}
