query Event($eventId: String!, $eventTickets: EventsTicketsSearchInput) {
  event(id: $eventId) {
    id
    name
    description
    visibility
    status
    startDateTime
    endDateTime
    tags {
      id
    }
    community {
      id
    }
    users {
      id
    }
    usersTickets(input: $eventTickets) {
      id
      approvalStatus
      paymentStatus
      redemptionStatus
      status
    }
  }
}
