/* eslint-disable */
/* @ts-nocheck */
/* prettier-ignore */
/* This file is automatically generated using `npm run graphql:types` */
import type * as Types from '../../../generated/types';

import type { JsonObject } from "type-fest";
import gql from 'graphql-tag';
export type EventsQueryVariables = Types.Exact<{
  input: Types.InputMaybe<Types.EventsSearchInput>;
}>;


export type EventsQuery = { __typename?: 'Query', events: Array<{ __typename?: 'Event', id: string, name: string, description: string | null, visibility: Types.EventVisibility, status: Types.EventStatus, startDateTime: string, endDateTime: string | null }> };


export const Events = gql`
    query Events($input: EventsSearchInput) {
  events(input: $input) {
    id
    name
    description
    visibility
    status
    startDateTime
    endDateTime
  }
}
    `;