/* eslint-disable */
/* @ts-nocheck */
/* prettier-ignore */
/* This file is automatically generated using `npm run graphql:types` */
import type * as Types from '../../../generated/types';

import type { JsonObject } from "type-fest";
import gql from 'graphql-tag';
export type CheckPurchaseOrderStatusMutationVariables = Types.Exact<{
  input: Types.CheckForPurchaseOrderInput;
}>;


export type CheckPurchaseOrderStatusMutation = { __typename?: 'Mutation', checkPurchaseOrderStatus: { __typename?: 'PurchaseOrder', id: string, status: Types.PurchaseOrderStatusEnum | null, paymentPlatform: string | null, purchasePaymentStatus: Types.PurchaseOrderPaymentStatusEnum | null, finalPrice: number | null, currency: { __typename?: 'AllowedCurrency', id: string, currency: string } | null } };


export const CheckPurchaseOrderStatus = gql`
    mutation CheckPurchaseOrderStatus($input: CheckForPurchaseOrderInput!) {
  checkPurchaseOrderStatus(input: $input) {
    id
    status
    currency {
      id
      currency
    }
    paymentPlatform
    purchasePaymentStatus
    finalPrice
  }
}
    `;