ALTER TABLE "allowed_currencies" ALTER COLUMN "created_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "allowed_currencies" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "allowed_currencies" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "communities" ALTER COLUMN "created_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "communities" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "communities" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "companies" ALTER COLUMN "created_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "companies" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "companies" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "confirmation_token" ALTER COLUMN "created_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "confirmation_token" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "confirmation_token" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "events" ALTER COLUMN "created_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "events" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "events" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "events_communities" ALTER COLUMN "created_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "events_communities" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "events_communities" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "events_tags" ALTER COLUMN "created_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "events_tags" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "events_tags" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "events_users" ALTER COLUMN "created_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "events_users" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "events_users" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "payments_logs" ALTER COLUMN "created_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "payments_logs" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "payments_logs" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "prices" ALTER COLUMN "created_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "prices" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "prices" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "purchase_orders" ALTER COLUMN "created_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "purchase_orders" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "purchase_orders" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "salaries" ALTER COLUMN "created_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "salaries" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "salaries" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "tags" ALTER COLUMN "created_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "tags" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "tags" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "tags_communities" ALTER COLUMN "created_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "tags_communities" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "tags_communities" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "teams" ALTER COLUMN "created_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "teams" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "teams" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "tickets_prices" ALTER COLUMN "created_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "tickets_prices" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "tickets_prices" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "tickets" ALTER COLUMN "created_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "tickets" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "tickets" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "created_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "users_communities" ALTER COLUMN "created_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "users_communities" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "users_communities" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "users_tags" ALTER COLUMN "created_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "users_tags" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "users_tags" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "user_teams" ALTER COLUMN "created_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "user_teams" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "user_teams" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "user_tickets" ALTER COLUMN "created_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "user_tickets" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "user_tickets" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "work_email" ALTER COLUMN "created_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "work_email" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "work_email" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "work_role" ALTER COLUMN "created_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "work_role" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "work_role" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "work_seniority" ALTER COLUMN "created_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "work_seniority" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "work_seniority" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "work_seniority_and_role" ALTER COLUMN "created_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "work_seniority_and_role" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (6);--> statement-breakpoint
ALTER TABLE "work_seniority_and_role" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp (6);