# 🚨 DEFAULT CONFIG 🚨
name = "wall-of-fame-cron"
compatibility_date = "2023-06-06"
main = "./index.ts"

[triggers]
# Schedule cron triggers:
# - Every 10 minutes
crons = ["*/10 * * * *"]

[define]
_APP_ENV = "'development'"






# =====================================
# =====================================
# 🚨 PRODUCTION CONFIG 🚨
# =====================================
# =====================================
[env.production.triggers]
# Schedule cron triggers:
# - Every 10 minutes
crons = ["*/10 * * * *"]

[env.production.define]
_APP_ENV = "'production'"






# =====================================
# =====================================
# 🚨 STAGING CONFIG 🚨
# =====================================
# =====================================

[env.staging.triggers]
# Schedule cron triggers:
# - Every 10 minutes
crons = ["*/10 * * * *"]

[env.staging.define]
_APP_ENV = "'staging'"
