# 🚨 DEFAULT CONFIG 🚨
name = "wall-of-fame-cron"
compatibility_date = "2023-06-06"
main = "./index.ts"

[vars]
# Variables should go here

[triggers]
# Schedule cron triggers:
# - Every day
crons = ["* */12 * * *"]

[define]
_APP_ENV = "'development'"


# =====================================
# =====================================
# 🚨 PRODUCTION CONFIG 🚨
# =====================================
# =====================================

[env.production.vars]
# Variables should go here

[env.production.triggers]
# Schedule cron triggers:
# - Every 1 minute
crons = ["*/1 * * * *"]

[env.production.define]
_APP_ENV = "'production'"


# =====================================
# =====================================
# 🚨 STAGING CONFIG 🚨
# =====================================
# =====================================
[env.staging.vars]
# Variables should go here

[env.staging.triggers]
# Schedule cron triggers:
# - Every day
crons = ["* */12 * * *"]

[env.staging.define]
_APP_ENV = "'staging'"
