# 🚨 DEFAULT CONFIG 🚨
name = "wall-of-fame-cron"
compatibility_date = "2023-06-06"
main = "./index.ts"
node_compat = true
upload_source_maps = true

[vars]
# Variables should go here

[triggers]
# Schedule cron triggers:
# - Every day
crons = ["* */1 * * *"]

[define]
_APP_ENV = "'development'"


# =====================================
# =====================================
# 🚨 PRODUCTION CONFIG 🚨
# =====================================
# =====================================
[env.production]
logpush = true

[env.production.vars]
# Variables should go here

[env.production.triggers]
# Schedule cron triggers:
# - Every 1 minute
crons = ["*/1 * * * *"]

[env.production.define]
_APP_ENV = "'production'"


# =====================================
# =====================================
# 🚨 STAGING CONFIG 🚨
# =====================================
# =====================================
[env.staging]
logpush = true

[env.staging.vars]
# Variables should go here

[env.staging.triggers]
# Schedule cron triggers:
# - Every day
crons = ["* */1 * * *"]

[env.staging.define]
_APP_ENV = "'staging'"
