mutation UpdateMyUserData($input: updateUserDataInput!) {
  updateMyUserData(input: $input) {
    id
    userData {
      city
      countryOfResidence
      organizationName
      roleInOrganization
      worksInOrganization
    }
  }
}
