/* eslint-disable */
/* @ts-nocheck */
/* prettier-ignore */
/* This file is automatically generated using `npm run graphql:types` */
import type * as Types from '../../generated/types';

import type { JsonObject } from "type-fest";
import gql from 'graphql-tag';
export type WorkRolesAndSenioritiesQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type WorkRolesAndSenioritiesQuery = { __typename?: 'Query', workRoles: Array<{ __typename?: 'WorkRole', description: string | null, id: string, name: string, seniorities: Array<{ __typename?: 'WorkSeniority', id: string, name: string, description: string | null }> }> };


export const WorkRolesAndSeniorities = gql`
    query WorkRolesAndSeniorities {
  workRoles {
    description
    id
    name
    seniorities {
      id
      name
      description
    }
  }
}
    `;