/* eslint-disable */
/* @ts-nocheck */
/* prettier-ignore */
/* This file is automatically generated using `npm run graphql:types` */
import type * as Types from '../../../../generated/types';

import type { JsonObject } from "type-fest";
import gql from 'graphql-tag';
export type AcceptTransferredTicketMutationVariables = Types.Exact<{
  transferId: Types.Scalars['String']['input'];
}>;


export type AcceptTransferredTicketMutation = { __typename?: 'Mutation', acceptTransferredTicket: { __typename?: 'UserTicketTransfer', id: string, status: Types.TicketTransferAttemptStatus, userTicket: { __typename?: 'UserTicket', id: string, user: { __typename?: 'User', id: string } | null } } };


export const AcceptTransferredTicket = gql`
    mutation AcceptTransferredTicket($transferId: String!) {
  acceptTransferredTicket(transferId: $transferId) {
    id
    status
    userTicket {
      id
      user {
        id
      }
    }
  }
}
    `;