query Communities(
  $communityID: String
  $communityName: String
  $communityStatus: CommnunityStatus
) {
  communities(
    id: $communityID
    name: $communityName
    status: $communityStatus
  ) {
    description
    id
    name
    status
  }
}
