/* eslint-disable */
/* @ts-nocheck */
/* prettier-ignore */
/* This file is automatically generated using `npm run graphql:types` */
import type * as Types from '../../../generated/types';

import type { JsonObject } from "type-fest";
import gql from 'graphql-tag';
export type TokensMutationVariables = Types.Exact<{
  input: Types.RetoolToken;
}>;


export type TokensMutation = { __typename?: 'Mutation', retoolToken: { __typename?: 'TokenRef', token: string } };


export const Tokens = gql`
    mutation Tokens($input: retoolToken!) {
  retoolToken(input: $input) {
    token
  }
}
    `;