/* eslint-disable */
/* @ts-nocheck */
/* prettier-ignore */
/* This file is automatically generated using `npm run graphql:types` */
import type * as Types from '../../../generated/types';

import type { JsonObject } from "type-fest";
import gql from 'graphql-tag';
export type CreateAddonMutationVariables = Types.Exact<{
  input: Types.AddonInput;
}>;


export type CreateAddonMutation = { __typename?: 'Mutation', createAddon: { __typename?: 'Addon', id: string } };


export const CreateAddon = gql`
    mutation CreateAddon($input: AddonInput!) {
  createAddon(input: $input) {
    id
  }
}
    `;