mutation CreateSalary($input: CreateSalaryInput!) {
  createSalary(input: $input) {
    id
    amount
    currencyCode
    yearsOfExperience
    countryCode
    gender
    genderOtherText
    typeOfEmployment
    workRole {
      id
      name
    }
    workMetodology
  }
}

mutation UpdateSalary($input: UpdateSalaryInput!) {
  updateSalary(input: $input) {
    id
    amount
    currencyCode
    yearsOfExperience
    countryCode
    gender
    genderOtherText
    typeOfEmployment
    workRole {
      id
      name
    }
    workMetodology
  }
}
