# 🚨 DEFAULT CONFIG 🚨
name = "google-import-queue-consumer"
compatibility_date = "2024-06-03"
main = "./index.ts"
upload_source_maps = true

[define]
_APP_ENV = "'development'"

[placement]
mode = "smart"

[[queues.consumers]]
queue = "google-photos-import-queue-dev"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 10
dead_letter_queue = "deadletter-google-photos-import-queue-dev"





# =====================================
# =====================================
# 🚨 PRODUCTION CONFIG 🚨
# =====================================
# =====================================
[env.production]
logpush = true

[env.production.define]
_APP_ENV = "'production'"

[env.production.placement]
mode = "smart"

[[env.production.queues.consumers]]
queue = "google-photos-import-queue-production"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 10
dead_letter_queue = "deadletter-google-photos-import-queue-production"





# =====================================
# =====================================
# 🚨 STAGING CONFIG 🚨
# =====================================
# =====================================
[env.staging]
logpush = true

[env.staging.define]
_APP_ENV = "'staging'"

[env.staging.placement]
mode = "smart"

[[env.staging.queues.consumers]]
queue = "google-photos-import-queue-staging"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 10
dead_letter_queue = "deadletter-google-photos-import-queue-staging"

