/* eslint-disable */
/* @ts-nocheck */
/* prettier-ignore */
/* This file is automatically generated using `npm run graphql:types` */
import type * as Types from '../../../../generated/types';

import type { JsonObject } from "type-fest";
import gql from 'graphql-tag';
export type RedeemUserTicketMutationVariables = Types.Exact<{
  userTicketId: Types.Scalars['String']['input'];
}>;


export type RedeemUserTicketMutation = { __typename?: 'Mutation', redeemUserTicket: { __typename?: 'UserTicket', id: string, status: Types.TicketStatus, paymentStatus: Types.TicketPaymentStatus, approvalStatus: Types.TicketApprovalStatus, redemptionStatus: Types.TicketRedemptionStatus } };


export const RedeemUserTicket = gql`
    mutation RedeemUserTicket($userTicketId: String!) {
  redeemUserTicket(userTicketId: $userTicketId) {
    id
    status
    paymentStatus
    approvalStatus
    redemptionStatus
  }
}
    `;