mutation CreateTicket($input: TicketCreateInput!) {
  createTicket(input: $input) {
    id
    name
    description
    status
    visibility
    startDateTime
    endDateTime
    isUnlimited
    requiresApproval
    quantity
    eventId
  }
}
