mutation EditTicket($input: TicketEditInput!) {
  editTicket(input: $input) {
    id
    name
    description
    status
    visibility
    isUnlimited
    startDateTime
    endDateTime
    requiresApproval
    quantity
    event {
      id
    }
  }
}
