mutation EditTicket($input: TicketEditInput!) {
  editTicket(input: $input) {
    id
    name
    description
    status
    visibility
    startDateTime
    endDateTime
    requiresApproval
    quantity
    eventId
  }
}
