/* eslint-disable */
/* @ts-nocheck */
/* prettier-ignore */
/* This file is automatically generated using `npm run graphql:types` */
import type * as Types from '../../../generated/types';

import type { JsonObject } from "type-fest";
import gql from 'graphql-tag';
export type SingleEventWithPricingQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type SingleEventWithPricingQuery = { __typename?: 'Query', events: Array<{ __typename?: 'Event', id: string, tickets: Array<{ __typename?: 'Ticket', id: string, prices: Array<{ __typename?: 'Price', id: string, amount: number, currency: { __typename?: 'AllowedCurrency', id: string, currency: string, validPaymentMethods: Types.ValidPaymentMethods } }> | null }> }> };


export const SingleEventWithPricing = gql`
    query SingleEventWithPricing {
  events {
    id
    tickets {
      id
      prices {
        id
        amount
        currency {
          id
          currency
          validPaymentMethods
        }
      }
    }
  }
}
    `;