query EventTickets($input: PaginatedInputEventsSearchInput!) {
  searchEvents(input: $input) {
    data {
      id
      name
      tickets {
        id
        name
        quantity
      }
    }
  }
}
