query SingleEventWithPricing {
  events {
    id
    tickets {
      id
      prices {
        id
        amount
        currency {
          id
          currency
          validPaymentMethods
        }
      }
    }
  }
}
