/* eslint-disable */
/* @ts-nocheck */
/* prettier-ignore */
/* This file is automatically generated using `npm run graphql:types` */
import type * as Types from '../../../generated/types';

import type { JsonObject } from "type-fest";
import gql from 'graphql-tag';
export type SingleEventWithPricingQueryVariables = Types.Exact<{
  input: Types.PaginatedInputEventsSearchInput;
}>;


export type SingleEventWithPricingQuery = { __typename?: 'Query', searchEvents: { __typename?: 'PaginatedEvent', data: Array<{ __typename?: 'Event', id: string, tickets: Array<{ __typename?: 'Ticket', id: string, prices: Array<{ __typename?: 'Price', id: string, amount: number, currency: { __typename?: 'AllowedCurrency', id: string, currency: string, validPaymentMethods: Types.ValidPaymentMethods } }> | null }> }> } };


export const SingleEventWithPricing = gql`
    query SingleEventWithPricing($input: PaginatedInputEventsSearchInput!) {
  searchEvents(input: $input) {
    data {
      id
      tickets {
        id
        prices {
          id
          amount
          currency {
            id
            currency
            validPaymentMethods
          }
        }
      }
    }
  }
}
    `;