query SingleEventWithPricing($input: PaginatedInputEventsSearchInput!) {
  searchEvents(input: $input) {
    data {
      id
      tickets {
        id
        prices {
          id
          amount
          currency {
            id
            currency
            validPaymentMethods
          }
        }
      }
    }
  }
}
