mutation GiftMyTicketToUser($ticketId: String!, $input: GiftInfoInput!) {
  giftMyTicketToUser(ticketId: $ticketId, input: $input) {
    id
    status
    expirationDate
    giftMessage
    gifter {
      email
      name
    }
    recipient {
      email
      name
    }
    userTicket {
      id
      approvalStatus
    }
  }
}
