/* eslint-disable */
/* @ts-nocheck */
/* prettier-ignore */
/* This file is automatically generated using `npm run graphql:types` */
import type * as Types from '../../../../generated/types';

import type { JsonObject } from "type-fest";
import gql from 'graphql-tag';
export type PublicTicketInfoQueryVariables = Types.Exact<{
  input: Types.PublicTicketInput;
}>;


export type PublicTicketInfoQuery = { __typename?: 'Query', publicTicketInfo: { __typename?: 'PublicUserTicket', id: string, userImage: string | null, userName: string | null, userUsername: string | null } };


export const PublicTicketInfo = gql`
    query PublicTicketInfo($input: PublicTicketInput!) {
  publicTicketInfo(input: $input) {
    id
    userImage
    userName
    userUsername
  }
}
    `;