/* eslint-disable */
/* @ts-nocheck */
/* prettier-ignore */
/* This file is automatically generated using `npm run graphql:types` */
import type * as Types from '../../generated/types';

import type { JsonObject } from "type-fest";
import gql from 'graphql-tag';
export type GetEventsQueryVariables = Types.Exact<{
  eventId: Types.Scalars['String']['input'];
  visibility: Types.InputMaybe<Types.EventVisibility>;
  status: Types.InputMaybe<Types.EventStatus>;
  startDateTime: Types.InputMaybe<Types.Scalars['Int']['input']>;
  endDateTime: Types.InputMaybe<Types.Scalars['Int']['input']>;
}>;


export type GetEventsQuery = { __typename?: 'Query', events: Array<{ __typename?: 'Event', id: string, name: string, description: string | null, visibility: Types.EventVisibility, status: Types.EventStatus, startDateTime: number, endDateTime: number | null }> };


export const GetEvents = gql`
    query getEvents($eventId: String!, $visibility: EventVisibility, $status: EventStatus, $startDateTime: Int, $endDateTime: Int) {
  events(
    input: {id: $eventId, visibility: $visibility, status: $status, startDateTime: $startDateTime, endDateTime: $endDateTime}
  ) {
    id
    name
    description
    visibility
    status
    startDateTime
    endDateTime
  }
}
    `;
