query Event($eventId: String!) {
  event(id: $eventId) {
    id
    name
    description
    visibility
    status
    startDateTime
    endDateTime
    tags {
      id
    }
    community {
      id
    }
    users {
      id
    }
    tickets {
      id,
      status,
      paymentStatus,
      approvalStatus,
      redemptionStatus
    }
  }
}
