/* eslint-disable */
/* @ts-nocheck */
/* prettier-ignore */
/* This file is automatically generated using `npm run graphql:types` */
import type * as Types from '../../generated/types';

import type { JsonObject } from "type-fest";
import gql from 'graphql-tag';
export type WorkEmailsQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type WorkEmailsQuery = { __typename?: 'Query', workEmails: Array<{ __typename: 'WorkEmail', id: string, isValidated: boolean }> };


export const WorkEmails = gql`
    query WorkEmails {
  workEmails {
    __typename
    id
    isValidated
  }
}
    `;