query CommunitiesUsers {
  communities {
    description
    id
    users {
      id
      communities {
        id
      }
    }
  }
}

query SingleCommunityUsers($id: String!) {
  community(id: $id) {
    description
    id
    users {
      id
      communities {
        id
      }
    }
  }
}
