/* eslint-disable */
/* @ts-nocheck */
/* prettier-ignore */
/* This file is automatically generated using `npm run graphql:types` */
import type * as Types from '../../../../generated/types';

import type { JsonObject } from "type-fest";
import gql from 'graphql-tag';
export type ClaimUserTicketMutationVariables = Types.Exact<{
  input: Types.TicketClaimInput;
}>;


export type ClaimUserTicketMutation = { __typename?: 'Mutation', claimUserTicket: { __typename: 'PurchaseOrder', id: string, paymentLink: string | null, paymentPlatform: string | null, tickets: Array<{ __typename?: 'UserTicket', id: string, paymentStatus: Types.PurchaseOrderPaymentStatusEnum | null, approvalStatus: Types.TicketApprovalStatus, redemptionStatus: Types.TicketRedemptionStatus, transferAttempts: Array<{ __typename?: 'UserTicketTransfer', id: string, sender: { __typename?: 'TicketTransferUserInfo', email: string, name: string | null }, recipient: { __typename?: 'TicketTransferUserInfo', email: string, name: string | null } }>, userTicketAddons: Array<{ __typename?: 'UserTicketAddon', id: string, quantity: number, approvalStatus: Types.UserTicketAddonApprovalStatus, addon: { __typename?: 'Addon', id: string, name: string } }> }> } | { __typename: 'RedeemUserTicketError', errorMessage: string } };


export const ClaimUserTicket = gql`
    mutation ClaimUserTicket($input: TicketClaimInput!) {
  claimUserTicket(input: $input) {
    __typename
    ... on PurchaseOrder {
      id
      paymentLink
      paymentPlatform
      tickets {
        id
        paymentStatus
        approvalStatus
        redemptionStatus
        transferAttempts {
          id
          sender {
            email
            name
          }
          recipient {
            email
            name
          }
        }
        userTicketAddons {
          id
          quantity
          approvalStatus
          addon {
            id
            name
          }
        }
      }
    }
    ... on RedeemUserTicketError {
      __typename
      errorMessage
    }
  }
}
    `;