mutation ClaimUserTicket($input: TicketClaimInput!) {
  claimUserTicket(input: $input) {
    __typename
    ... on PurchaseOrder {
      id
      tickets {
        id
        paymentStatus
        approvalStatus
        redemptionStatus
        giftAttempts {
          id
          gifter {
            email
            name
          }
          receiver {
            email
            name
          }
        }
      }
    }
    ... on RedeemUserTicketError {
      __typename
      errorMessage
    }
  }
}
