mutation ClaimUserTicket($input: TicketClaimInput!) {
  claimUserTicket(input: $input) {
    ... on UserTicket {
      id
      status
      paymentStatus
      approvalStatus
      redemptionStatus
    }
    ... on RedeemUserTicketError {
      __typename
      errorMessage
    }
  }
}
