mutation ClaimUserTicket($input: TicketClaimInput!) {
  claimUserTicket(input: $input) {
    __typename
    ... on PurchaseOrder {
      id
      paymentLink
      paymentPlatform
      tickets {
        id
        paymentStatus
        approvalStatus
        redemptionStatus
        transferAttempts {
          id
          sender {
            email
            name
          }
          recipient {
            email
            name
          }
        }
        userTicketAddons {
          id
          quantity
          approvalStatus
          addon {
            id
            name
          }
        }
      }
    }
    ... on RedeemUserTicketError {
      __typename
      errorMessage
    }
  }
}
