name: Deploy to DEV

on:
  workflow_run:
    # Esto tiene q hacer match con los nombres de los workflows de tests
    workflows: ["Graphql and Database Tests", "Lint and Typecheck"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy to Cloudflare Workers
    runs-on: ubuntu-latest
    steps:
      - name: ⏳ Cloning repo
        uses: actions/checkout@v3
      - name: ⬢ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 📦 Cache Package Dependencies
        uses: actions/cache@v3
        env:
          cache-name: DEV
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ env.cache-name }}
      - name: 📥 Download deps
        run: npm ci --prefer-offline --no-audit --cache ~/.npm
      - name: 🚀 Deploy to Cloudflare Workers
        uses: demosjarco/wrangler-action-node@v1.1.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_WORKERS_JSCONF_DEV_DEPLOY }}
          wranglerVersion: "3.1.2"
          command: deploy
