name: Deploy to DEV

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    name: Deploy to Cloudflare Workers — DEV
    runs-on: ubuntu-latest
    steps:
      - name: ⏳ Cloning repo
        uses: actions/checkout@v3
      - name: ⬢ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 📦 Download Cached Package Dependencies
        uses: actions/cache@v3
        env:
          cache-name: NPM
        with:
          path: ~/.npm
          key: CACHE-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: 📥 Install dependencies
        run: npm ci --prefer-offline --no-audit --legacy-peer-deps --cache ~/.npm
      - name: 💀 Remove queue consumer
        run: CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_WORKERS_JSCONF_DEV_DEPLOY }} npx wrangler queues consumer remove mail-queue-dev graphql-api-dev
      - name: 🛳️ DEPLOY Cloudflare Workers
        run: CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_WORKERS_JSCONF_DEV_DEPLOY }} npx wrangler deploy
